naw = {
    "schema_name": "naw",
    "schema_version": "1.0",
    "attributes": [
        "naam",
        "voorletters",
        "achternaam",
        "geslacht",
        "geboortedatum",
        "geboorteland",
        "bsn",
        "geldigheid_id",
        "burgelijke_staat",
        "telefoonnummer",
        "email-adres",
        "straat",
        "huisnummer",
        "toevoeging",
        "postcode",
        "woonplaats",
        "provincie",
        "land",
        "polisnummer",
        "verzekeraar",
        "voornaam_mantelzorger",
        "tussenvoegsel_mantelzorger",
        "achternaam_mantelzorger",
        "telefoonnummer_mantelzorger",
        "mobielnummer_mantelzorger",
        "email-adres_mantelzorger",
        "voornaam_contactpersoon",
        "tussenvoegsel_contactpersoon",
        "achternaam_contactpersoon",
        "telefoonnummer_contactpersoon",
        "mobielnummer_contactpersoon",
        "email-adres_contactpersoon",
        "naam_huisarts",
        "straat_huisarts",
        "huisnnummer_huisarts",
        "toevoeging_huisarts",
        "telefoonnummer_huisarts",
        "agb-code_huisarts",
        "uzi-nummer_huisarts",
        "email-adres_huisarts"
    ]
}
